### ISSUE TITLE
Teach the IOMMU framework to handle COPROC devices

### ISSUE THREAD

**Issue by otyshchenko1** [otyshchenko1/xen#4]
The IOMMU code should handle devices marked as xen,coproc in other specific way. These devices are shared between domains, so they might be assigned to several domains at the same time.

**Comment by aanisov** [comment]
Are you sure IOMMU framework should  handle xen,coproc devices by itself? Wouldn't it be better to provide a "generic" implementation of device migration during domains runtime, together with an interface to create/init such a migrating devices?
